const h = {
  level: 30,
  time: 1738264179003,
  pid: 462922,
  hostname: 'polsito-Lenovo-IdeaPad-S145-15IIL',
  req: {
    id: 3,
    method: 'POST',
    url: '/graphql',
    query: {},
    params: { '0': 'graphql' },
    headers: {
      'accept': '*/*',
      'authorization':
        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjc5YmE0NmViOTFjMGZlY2YwNTEyYTNiIiwiaWF0IjoxNzM4MjY0MTc4LCJleHAiOjE3Mzg4Njg5Nzh9.OQguhjbgUnQ2SlOsdXTaKD3pkKCscf9hcUEegWm1wZ4',
      'content-type': 'application/json',
      'content-length': '2309',
      'host': '192.168.43.231:57343',
      'connection': 'Keep-Alive',
      'accept-encoding': 'gzip',
      'user-agent': 'okhttp/4.12.0',
    },
    remoteAddress: '::ffff:192.168.43.1',
    remotePort: 43382,
  },
  res: {
    statusCode: 200,
    headers: {
      'vary': 'Origin',
      'access-control-allow-credentials': 'true',
      'content-security-policy':
        "img-src 'self' data: apollo-server-landing-page.cdn.apollographql.com;script-src 'self' https: 'unsafe-inline';manifest-src 'self' apollo-server-landing-page.cdn.apollographql.com;frame-src 'self' sandbox.embed.apollographql.com;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'cross-origin-opener-policy': 'same-origin',
      'cross-origin-resource-policy': 'same-origin',
      'origin-agent-cluster': '?1',
      'referrer-policy': 'no-referrer',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      'x-ratelimit-limit': '50',
      'x-ratelimit-remaining': '49',
      'x-ratelimit-reset': '60',
      'cache-control': 'no-store',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '41',
      'etag': 'W/"29-E/ys+n5SZrOSbjDHuKqQSU9A9nI"',
    },
  },
  responseTime: 327,
  msg: 'request completed',
};
