export const NEO4J_CONFIG: string = 'NEO4J_CONFIG';
export const NEO4J_DRIVER: string = 'NEO4J_DRIVER';

export enum NEO4J_NODES {
  DISEASES = 'DISEASES',
  DISEASE_CAUSES = 'DISEASE_CAUSES',
  NUTRITIONAL_PREFERENCES = 'NUTRITIONAL_PREFERENCES',
}
