export const spanishLabelMap: Record<string, string> = {
  'CA': 'Calcio',
  'CHOCDF.net': 'Carbohidratos netos',
  'CHOCDF': 'Carbohidratos',
  'CHOLE': 'Colesterol',
  'ENERC_KCAL': 'Energía',
  'FAMS': 'Ácidos grasos monoinsaturados',
  'FAT': 'Grasas',
  'FAPU': 'Ácidos grasos poliinsaturados',
  'FASAT': 'Ácidos grasos saturados',
  'FATRN': 'Grasa trans',
  'FIBTG': 'Fibra dietética',
  'FOLDFE': 'Folato (DFE)',
  'FOLFD': 'Folato',
  'FOLAC': 'Acido fólico',
  'FE': 'Hierro',
  'K': 'Potasio',
  'MG': 'Magnesio',
  'NA': 'Sodio',
  'NIA': 'Niacina',
  'P': 'Fósforo',
  'PROCNT': 'Proteínas',
  'RIBF': 'Riboflavina',
  'SUGAR': 'Azúcares',
  'Sugar.alcohol': 'Alcoholes de azúcar',
  'SUGAR.added': 'Azúcares añadidos',
  'THIA': 'Tiamina',
  'TOCPHA': 'Vitamina E (alpha-tocopherol)',
  'VITA_RAE': 'Vitamina A (RAE)',
  'VITB12': 'Vitamina B-12',
  'VITB6A': 'Vitamina B-6',
  'VITC': 'Vitamina C',
  'VITD': 'Vitamina D (D2 + D3)',
  'VITK1': 'Vitamina K (phylloquinone)',
  'WATER': 'Agua',
  'ZN': 'Zinc',
};
